build_site:
  tags:
    - ci
  image: node:latest
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:latest
  stage: test
  script:
    - npm install --progress=false
    - npm run test:unit
