build_site:
  tags:
    - ci
  image: node:latest
  stage: build
  script:
    - npm install --progress=false
    - npm run build
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - dist

unit test:
  tags:
    - ci
  image: node:latest
  stage: test
  script:
    - npm install --progress=false
    - npm run test:unit
pages:
  tags:
    - ci
  image: node:latest
  stage: deploy
  script:
    - npm install --progress=false
    - npm run build
    # - rm -rf public
    - mkdir public
    - cp -r dist/* public
  artifacts:
    expire_in: 1 day
    paths:
      - public
